version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=worklog-management
      - MYSQL_USER=worklog-management
      - MYSQL_PASSWORD=worklog-management
    ports:
      - 3306:3306