server:
  port: 8080
  servlet:
    contextPath: /chronos
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/worklog-management?autoReconnect=true&useSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
    database-platform: org.hibernate.dialect.MySQL5Dialect